### ISSUE TITLE
"My teams" API route

### ISSUE THREAD

**Issue by kamicut** [developmentseed/osm-teams#145]
a "My teams" API route returns data about the teams the authenticated user is a part of, and which teams this user moderates.

**Comment by guidorice** [comment]
@kamicut I started to add a function in `app/manage/teams.js` that is very similar to the existing `listTeams(req, reply)`. The new function needs to get the authenticated user's OSM id. For browser interactions this is no problem as there is a session middleware, so we have in the `req.session` the following properties:

```
teams_1  | [
teams_1  |   "cookie",
teams_1  |   "login_csrf",
teams_1  |   "idToken",
teams_1  |   "user_id",
teams_1  |   "user",
teams_1  |   "user_picture"
teams_1  | ]
```

However, if interacting with the API via a [bearer token](https://gist.github.com/guidorice/72a3748fe3a8b57d1f988690a206054f) then there is no session. The same dump of `req.session` properties:

```
teams_1  | [
teams_1  |   "cookie"
teams_1  | ]
```

I believe interacting with the API via a bearer token is important for 

1. development ergonomics (don't want to use the browser for every test and iteration of development cycle)
2. access to the API programmatically by users outside of the browser.

### Possible solution:

Extend the session middle-ware to detect a bearer token and setup the same session data structure as shown at the top, to include at least the user_id, user and user_picture. And whatever else is required (login_csrf?)

I am really not sure if this proposal makes much sense but wanted to raise the idea. If you agree, then I would open a separate enhancement issue because it's bigger than this current issue.

For me it raises the question: in general how are sessions and bearer tokens reconciled so you can have the same api functionality no matter how a user authenticated. I would want to do some due diligence and see how this is done in next.js (or in auth systems in general).

**Comment by kamicut** [comment]
@guidorice, in the case of the API the bearer token is traded for an access token in this route function (https://github.com/developmentseed/osm-teams/blob/master/app/manage/permissions/index.js#L94-L103). This allows us to get the `user_id` from the bearer token in the permissions middleware.

**Comment by guidorice** [comment]
@kamicut Great, that looks promising. Let's talk tomorrow for more ideas- I'm not clear on exactly how it would tie together in this My Teams route for example.

**Comment by guidorice** [comment]
During the scrum call today @kamicut pointed out a couple of helpful things:

- in express apps, the auth info is commonly stored in the `response` or `reply` object after the auth middleware has processed it. 
- for example this is done already in https://github.com/developmentseed/osm-teams/blob/master/app/manage/teams.js#L52

Todo
- [ ]  check if this still works when accessed with a bearer token (it should:
