### ISSUE TITLE
Awkward UX-flow for joining from invite link

### ISSUE THREAD

**Issue by jenningsanderson** [developmentseed/osm-teams#318]
When invited to join a team on OSM Teams, a user must first be logged into OSM Teams to accept the link, otherwise they are prompted to first log-in.

When a user logs in, they are always redirected to their main profile page, not back to the team invite.

I refer mappers to this video for instructions: https://vimeo.com/724683103 — but it would be great if the UX flow can start with just the invite link, go to OSM Teams, log-in via OSM, and then bring the user right back to accept the invite.

Multiple times, users have gone to OSM Teams, logged in, and then created their own team (with their username as the team name), instead of going back to the original invite link.

**Comment by batpad** [comment]
I think redirecting a user correctly to where they initially wanted to go after logging in is pretty critical - I'd really like to see that fixed rather than coming up with workarounds.

@kamicut @vgeorge - I know this is always complex to get right, but I believe it's something one just has to do - let's try and scope out options for how best to achieve this and then we can see how best to prioritize.

Thanks for the ticket @jenningsanderson !

**Comment by batpad** [comment]
I believe this is fixed. @vgeorge please re-open if there is anything pending here.
