### ISSUE TITLE
Improve map on Organization page

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-teams#437]
Adding this issue to track - 

We should be able to visualize all teams in an organization on the map (and not just the ones returned on the current page) and have filters applied to the map as well as the table.

Am a bit fuzzy on the details, so please add details, @kamicut @jenningsanderson

**Comment by jenningsanderson** [comment]
Sure thing, some details with the YouthMappers Org. as example:

On the main organization page, we see a map and a table of teams (perfect):
![image](https://user-images.githubusercontent.com/1637425/230674801-3bd1f5d7-cd6c-49d7-9579-65f6a38cc270.png)

However, the org has 263 teams and the map is only showing the first 10 teams (because of the pagination).

When you click next on the table, it loads the following 10 teams, but the map does not change to reflect the new team locations.

### Desired Behavior: 
1. The map should show all 263 dots representing the location of all of the teams (or at least those with a set location).
2. The map should also be able to offer a spatial filter that also affects the table, in the same way it does on the main "explore" page at https://mapping.team/teams
