### ISSUE TITLE
Add support for bulk import of usernames

### ISSUE THREAD

**Issue by geomantic** [developmentseed/osm-teams#457]
Teachers are interested in integrating OSM-teams into their mapping events to manage their participating mappers. Currently, they have to enter OSM usernames one-by-one. For a teacher with 3 classes of 30 students it is time-consuming and a lot of work. Teachers need a way to bulk import (csv?) lists of students with their OSM usernames.

**Comment by jenningsanderson** [comment]
@geomantic! I think I have your solution. Each team has an invite link that's unique — to that team. You can share that link with your students and it will let them join the team via their OSM username. 

This is desirable because if you are collecting usernames manually and there is a typo or a capitalization issue, it will be wrong... this is why we added the join link. 

Additionally, if you'd like to add other attributes for your mappers to fill out alongside their OSM teams profile (i.e., if you want to collect any additional information from the mappers), the join link will bring them directly to the profile page where they can enter that information.

Would love to share more details on this, send me a message!

**Comment by kamicut** [comment]
@geomantic The Invite Link and the API can cover this functionality. A separate Bulk import tool could be built outside of the main repo. I will close this issue but please continue to use it for discussion.
