### ISSUE TITLE
Token Error on login

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#87]
After logging in, I am often thrown to a page with the correct URL `/profile` but the only rendered text is the object here:
```
{"0":"B","1":"e","2":"a","3":"r","4":"e","5":"r","statusCode":401,"error":"Unauthorized","message":"No token","attributes":{"error":"No token"}}
```

I am unable to predict when this occurs, but it happens 75% of the time. Might be related to #29

**Comment by sethvincent** [comment]
So far I haven't been able to replicate this. My guess is that this happens after a token expires.

I'm pretty sure that in pr #86 I removed the thing that was making this weird stuff happen `"0":"B","1":"e","2":"a","3":"r","4":"e","5":"r",` https://github.com/developmentseed/osm-teams/pull/86/files#diff-591d424b0fd83cf94816bc83f9ba26d6L36

So I'm hoping there's at least some chance that pr resolved this issue. Or that pr might have changed the behavior in some way.

**Comment by kamicut** [comment]
I think this has to do with intermittent disconnection of local servers to the staging database. We are probably maxing out the connections and once that happens, all sorts of errors happen because either the app or hydra can't connect to the database. @sethvincent I think you are not getting this because you're using a local database.
